#+TITLE: Chapter 3 - Displaying Categorical Data

*Categorical data*, also known as /qualitative data/, is data that can be divided into categories or qualities
  
* Vocabulary

- *frequency table* - a table that shows how frequent a specific category is
- *proportion* - describes the quantity of the frequency
- *relative frequency distribution* - what proportion did something happen
- *distribution* - how the data is spread out, usually how it is spread out graphically
- *area principle* -
- *contingency table* - a table that displays data involving several independent variables
- *marginal distribution* - a distribution that takes in the totals of contingency data
- *conditional distribution* - a distribution that takes in a condition (e.g. given the value of an independent variable)
- *independence of variables* - using probability to mathematically prove if two variables are correlated or have a specific relationship

* Bar Graphs and Histograms

Bar graphs and histograms require a /specific/ and /descriptive/ title.

Bar graphs can be segmented into different qualities or categories while also being aggregated at the same time. The bars *must have space between them* to quality as a bar graph.

A histogram's independent variables are separated by quantitative intervals rather than categories. Histograms *can not have space between the bars* unlike bar graphs.

* Simpson's Paradox

Trevor and Matt are competing to be the starting quarterback of a football team. During practice, the coaches totaled up the data and found this:

|        |  SP | SPC | LP | LPC |
|--------+-----+-----+----+-----|
| Trevor |  74 |  51 | 47 |  11 |
| Matt   | 161 |  97 | 20 |   1 |

** Example 1:

The CDC lists causes of death in the United States during 1999.

| Cause of Death | Percent |
|----------------+---------|
| Heart Disease  |    30.3 |
| Cancer         |    23.0 |
| Circulatory    |     8.4 |
| Respiratory    |     7.9 |
| Accidents      |     4.1 |
| /Complement/     |    26.3 |
#+TBLFM: @>$2=100-vsum(@2..@-1)

a. Is it reasonable to conclude that heart or respiratory diseases were the cause of approximately 38% of U.S. deaths in 1999?

Yes, because the percentages add up, and the categories and title were relevant.

b. What percent of deaths were from causes not listed here?

Since the causes of death are a proportion that add up to 100%, the complement would be the percentage not listed.

* Marginal Distribution

#+PLOT: title:"Racial groups and education/employment" ind:1 type:2d with:boxes
#+TBLNAME: Racial groups and education/employment
|            | White | Minority | Total |
|------------+-------+----------+-------|
| Four year  |   198 |       44 |   242 |
| Two year   |    36 |        6 |    42 |
| Military   |     4 |        1 |     5 |
| Employment |    14 |        3 |    17 |
| Other      |    16 |        3 |    19 |
| Total      |   268 |       57 |   325 |
#+TBLFM: $>=vsum($2..$-1)
#+TBLFM: @>=vsum(@2..@-1)

1. What percent of the graduates are white?

   $P(w) = \frac{268}{325} = 82.4\%$

2. What percent of the graduates are planning to attend a 2-yr college?
   
   $P(2) = \frac{42}{325} = 12.9\%$

3. What percent of the graduates are white AND planning to attend a 2-yr college?

   $P(w \cap 2) = 11\%$

4. What percent of the white graduates are planning to attend a 2-yr college?

   $P(2 | w) = 13.4\%$

5. What percent of the graduates planning to attend a 2-yr colege are white?

   $P(w|2) = 85.7\%$

