#+TITLE: Chapter 8 - Sequences
#+DATE: <2021-09-02 Fri>

A sequence is a collection of terms that follows a general rule, or an
equation, which develops a pattern.

- term - element of a sequence

* General Rule
:PROPERTIES:
:CUSTOM_ID: general-rule
:END:
\[ a_n = \frac{(-1)^n}{2n - 1} \]

Where \(n\) is the term number, and \(n\) must be a positive integer.

\[ a_1 = \frac{(-1)^1}{2(1) - 1} = -1 \],

\[ a_2 = \frac{(-1)^2}{2(2) - 1} = \frac{1}{3} \],

\[ a_3 = \frac{(-1)^3}{2(3) - 1} = -\frac{1}{5} \],

\[ a_4 = \frac{(-1)^4}{2(4) - 1} = \frac{1}{7} \],

\[ a_5 = \frac{(-1)^5}{2(5) - 1} = -\frac{1}{9}  \],

** Factorial List
:PROPERTIES:
:CUSTOM_ID: factorial-list
:END:
\[ 0! = 1 \]

\[ 1! = 0!(1) = 1 \]

\[ 2! = 1!(2) = 2 \]

\[ 3! = 2!(3) = 6 \]

\[ 4! = 3!(4) = 24 \]

\[ 5! = 4!(5) = 120 \]

\[ 6! = 5!(6) = 720 \]

** Examples
:PROPERTIES:
:CUSTOM_ID: examples
:END:
1. Write an expression for the nth term of each sequence

\[ 1, 3, 5, 7, ... = 2n - 1 \]

\[ -2, 1, 6, 13, 22 = x^2 - 3 \]

\[ \frac{1}{2}, \frac{1}{2}, \frac{3}{4}, \frac{3}{2}, \frac{15}{4}, \frac{45}{4} = \frac{n!}{2^n} \]

2. [@2] Simplify these expressions

\[ \frac{10!}{7!} = 10 \cdot 9 \cdot 8 = 720 \]

\[ \frac{(n - 1)!}{(n + 1)!} = \frac{1}{n(n + 1)} = \frac{1}{n^2 + n} \]

** Fibonacci Sequence
:PROPERTIES:
:CUSTOM_ID: fibonacci-sequence
:END:
\[ a_n = a_{n - 1} + a_{n - 2}, a_1 = 1, a_2 = 2 \]

* Arithmetic Sequences
:PROPERTIES:
:CUSTOM_ID: arithmetic-sequences
:END:
Arithmetic sequences have a common difference between each term that
adds or subtracts to the next term.

*General explicit rule:* \(a_n = a_1 + d(n - 1)\)

*General recursive rule:* \(a_n = a_{n - 1} + d\)

** Examples
:PROPERTIES:
:CUSTOM_ID: examples-1
:END:
1. Find the general rule \(a_n\) for the sequence 5, 8, 11, 14, ...

\[ d = 3 \]

\[ a_n = d(n - 1) + 5 \]

\[ a_n = 3n + 2 \]

2. [@2] Find the general rule \(a_n\) for the sequence
   \(a_1, a_1 + d, a_1 + 2d\)

\[ a_n = d(n - 1) + a_1 \]

3. [@3] What is the 4th term of an arithmetic sequence whose first term
   is 7 and common difference is -2?

\[ a_n = -2(n - 1) + 7 \]

\[ a_4 = -2(4 - 1) + 7 = 1 \]

4. [@4] What is the 872nd term of the previous arithmetic sequence?

\[ a_{872} = -2(871) + 7 = -1742 + 7 = -1735 \]

** Partial Sum of an Arithmetic Sequence
:PROPERTIES:
:CUSTOM_ID: partial-sum-of-an-arithmetic-sequence
:END:
\[ S_n = \frac{n(a_1 + a_n)}{2} \]

* Geometric Sequences
:PROPERTIES:
:CUSTOM_ID: geometric-sequences
:END:
Geometric sequences have a common ratio between each term that
multiplies to the next term.

If \(|r| > 1\) then the sequence will generally increase. If
\(0 < |r| < 1\), then the sequence will generally decrease. If \(r < 0\)
then the sequence will alternate signs.

*General explicit rule:* \(a_n = a_1 \cdot r^{n - 1}\)

*General recursive rule:* \(a_n = r \cdot a_{n - 1}\)

** Finding Common Ratio Given Two Terms
:PROPERTIES:
:CUSTOM_ID: finding-common-ratio-given-two-terms
:END:
\[ r = \sqrt[m - n]{\frac{a_m}{a_n}} \]

** Examples
:PROPERTIES:
:CUSTOM_ID: examples-2
:END:
1. What is the general rule for the geometric sequence 2, 14, 98, ...

\[ a_n = 2 \cdot 7^{n - 1} \]

2. [@2] Find a_10 for the geometric sequence where \(r = \frac{1}{2}\)
   and \(a_4 = 125\)

\[ a_{10} = a_4 \cdot \frac{1}{2}^6 = \frac{125}{64} \]

** Partial Sum of a Geometric Sequence
:PROPERTIES:
:CUSTOM_ID: partial-sum-of-a-geometric-sequence
:END:
\[ S_n = a_1(\frac{1 - r^n}{1 - r}) \]

*** Example
:PROPERTIES:
:CUSTOM_ID: example
:END:
1. Evaluate \(\sum_{n = 1}^{12} 4(0.3)^n\)

\[ S_n = 1.2(\frac{1 - 0.3^{12}}{1 - 0.3}) = 1.714 \]

** Sum of an Infinite Geometric Series
:PROPERTIES:
:CUSTOM_ID: sum-of-an-infinite-geometric-series
:END:
Given \(|r| < 1\)

\[ S_{\infty} = \frac{a_1}{1 - r} \]

*** Proof
:PROPERTIES:
:CUSTOM_ID: proof
:END:
Given the geometric sequence \(a_n = a_1 \cdot r^{n - 1}\)

*** Examples
:PROPERTIES:
:CUSTOM_ID: examples-3
:END:
1. Evaluate \(\sum_{n = 1}^{\infty} 4(\frac{1}{2})^n\)

#+begin_html
  <center>
#+end_html

\(\frac{2}{\frac{1}{2}} = 4\), therefore this series converges to 4.

#+begin_html
  </center>
#+end_html

2. [@2] Evaluate \(\sum_{n = 1}^{\infty} 4(2)^n\)

#+begin_html
  <center>
#+end_html

\(|r| \ge 1\), therefore this series diverges to \(\infty\).

#+begin_html
  </center>
#+end_html

* Proof by Mathematical Induction
:PROPERTIES:
:CUSTOM_ID: proof-by-mathematical-induction
:END:
** Formal Types of Logical Reasoning
:PROPERTIES:
:CUSTOM_ID: formal-types-of-logical-reasoning
:END:
*Deductive reasoning* is a logical process in which a conclusion ins
based on the concordance of multiple premises that are generally assumed
to be true

*Inductive reasoning* starts with a generalization, and then test it by
applying it to specific incidents.

** Process of Inductive Reasoning
:PROPERTIES:
:CUSTOM_ID: process-of-inductive-reasoning
:END:
1. Show that your statement is true for its initial occurrence.

2. Make the assumption that it will be true for any arbitrarily selected
   trial of the rule.

3. Prove that it will be true for the term after the arbitrarily
   selected trial.

** Example
:PROPERTIES:
:CUSTOM_ID: example-1
:END:
1. Prove that \(1 + 3 + 5 + 7 + ... + (2k - 1) = k^2\)

Prove for 1st term \(k = 1\)

\[ 2(1) - 1 = 1^2 \]

Assume \(1 + 3 + 5 + 7 + ... + (2k - 1) = k^2\)

Prove for \(k + 1\)

\[ 1 + 3 + 5 + 7 + ... + (2k - 1) + (2(k + 1) - 1) = (k + 1)^2 \]

2. [@2] Prove that
   \(1 + 4 + 9 + 16 + ... + n^2 = \frac{n(n + 1)(2n + 1)}{6}\)

Prove for 1st term \(n = 1\)

\[ 1^2 = \frac{(2)(3)}{6} \]

Assume \(1 + 4 + 9 + 16 + ... + n^2 = \frac{n(n + 1)(2n + 1)}{6}\)

Prove for \(n + 1\)

$$ 1 + 3 + 5 + 7 + ... + n^2 + (n + 1)^2 =
\frac{(n + 1)(n + 2)(2n + 3)}{6}
