#+TITLE: Limits
#+DATE: <2022-01-31 Mon>
#+STARTUP: latexpreview

* Introduction to Calculus
** Three parts of calculus
+ Limits
** Calculus approach to mathematics
+ G - graphical/geometric
+ N - numerical
+ A - analytical/algebraic
+ W - words

* Introduction to Limits

** What can occur in $f(x)$ at an arbitrarily value of $x$?

+ Removable discontinuity
+ Vertical asymptote
+ Jump discontinuity
+ A point

** What are examples of approaching?

+ History grade approaching zero
+ Russia approaching Ukraine
+ Queen Elizabeth approaching immortality
+ Approaching = going towards, whether it will make it or not

** Examples

*** Example 1

$$
\lim_{x \to 1} \frac{x^3 - 1}{x - 1}
$$

$\to$ = "approaches"

Factoring the expression, we get $x^2 + x + 1$

This expression returns 3 when $x = 1$, while it does not exist in the original
function. However, limits do not care whether or not the value actually exists,
but rather where it would be approaching. Therefore,

$$
\lim_{x \to 1} \frac{x^3 - 1}{x - 1} = 3
$$

*** Example 2

$$
\lim_{x \to 0} \frac{x}{\sqrt{x + 1} - 1}
$$

When $x = 0$, we get $\frac{0}{0}$, which is not undefined, but
indeterminate. This means we have to find other methods for solving
this problem.

$$
\lim_{x \to 0} \frac{x}{\sqrt{x + 1} - 1} \cdot \frac{\sqrt{x + 1} +
1}{\sqrt{x + 1} + 1} = \lim_{x \to 0} \frac{x(\sqrt{x + 1} + 1)}{x + 1 - 1} =
\lim_{x \to 0} (\sqrt{x + 1} + 1) = 2
$$

*** Example 3

$$
\lim_{x \to 0} f(x)
$$

| x    | -2 | -1 |   0 |   1 |  2 |
|------+----+----+-----+-----+----|
| f(x) |  3 | 10 | Err | -10 | -3 |

The graph gradually increases from $[-2, 0)$ and decreases from $(0, 2]$. That
means there is an asymptote at 0; therefore,

$$
\lim_{x \to 0} f(x) = \textrm{DNE}
$$

*** Example 4


$f(x) = $

$$\left\{
\begin{array}{ll}
1 & x \neq 2 \\
-1 & x = 2
\end{array}
$$

$$
\lim_{x \to 2} f(x)
$$

When graphed, it would be the line $y = 1$ with a removable discontinuity at $x = 2$.

*** Example 5

\[
\lim_{x \to 0} \frac{x}{|x|}
\]

The left hand limit is -1, but the right hand limit is 1. Therefore,

\[
\lim_{x \to 0} \frac{x}{|x|} = \textrm{DNE}
\]

*** Example 6

\[
\lim_{x \to 0} \frac{1}{x^2}
\]

\[
\lim_{x \to 0^{+}} \frac{1}{x^2}
\]
The limit from the left approaches $\infty$. The limit from the right approaches $\infty$. Therefore,

\[
\lim_{x \to 0} \frac{1}{x^2} = \infty
\]

*** Example 7

\[
\lim_{x \to 0} sin(\frac{1}{x})
\]

When graphed, the frequency of the oscillations increase as you approach 0, and
it is impossible to determine the limit from the graph.
